name: Backend CI/CD
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Add your backend deployment steps here, e.g.:
      # - run: npm install
      # - run: npm run build
      # - run: npm run deploy
